account/models/Application.php
<?php

namespace frontend\account\models;

//use common\models\User;
use Yii;
use yii\web\UploadedFile;
use frontend\account\models\AppRecipients;

class Application extends \yii\db\ActiveRecord
{
    public $file;
    public $recipients;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'application';
    }

    /**
     * @inheritdoc
     */

    public function rules()
    {
        return [
            [['title_app', 'description_app', 'category_app','recipients'], 'required'],
            [['user_id', 'id_folder', 'id_prod'], 'integer'],
            [['description_app'], 'string'],
            [['title_app', 'url_app', 'category_app'], 'string', 'max' => 255],
            [['file'], 'file', 'maxFiles' => 10, 'extensions' => 'doc, txt, rtf, jpg, png, pdf, jpeg', 'maxSize' => 3000000,'tooBig' => 'Max size is 3mb'],
            [['recipients'], 'each', 'rule'=> ['integer']],



        ];

    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'title_app' => 'Name of application',
            'url_app' => 'Files',
            'description_app' => 'Description',
            'id_folder' => 'Folder',
            'id_prod' => 'Products',
            'category_app' => 'Category',
        ];
    }

    public function uploadApp()
    {

        if (Yii::$app->request->isPost) {
            $user_id = \Yii::$app->user->identity->id;
                 $this->file = UploadedFile::getInstances($this, 'file');
                $uploads = "";
                foreach ($this->file as $file) {
                    $name = rand(111, 999) . '_' . $file->baseName . '.' . $file->extension;
                    $file->saveAs(Yii::getAlias('@media') . '/application/new_app/' . $name);
                    $uploads .= $name . '|';
                }
                $this->url_app = substr($uploads, 0, -1);

            $this->user_id = $user_id;


                if ($this->save(false)) {
                    $last_id = $this->id_app;
                    foreach($this->recipients as $to){
                        $model = new AppRecipients();
                        $model->from = $user_id;
                        $model->to = $to;
                        $model->app_id = $last_id;
                        $model->status = 0;
                        $model->save();
                    }
                    return true;
                }
            //}
        }
    }
    public static function findFolder($id_folder){
        $image = (new \yii\db\Query())
            ->select(['p.miniature_img'])
            ->from(['p' => 'products_list','o' => 'orders'])
            ->where('p.id_prod=o.id_prod')->andWhere(['o.id_folder' => $id_folder])->limit(4)->all();
        $folder = (new \yii\db\Query())->from('order_folder')->where(['id_folder' => $id_folder, 'parent_status'=>0])->one();
        return array(['image'=>$image, 'folder'=>$folder]);
    }
    public static function findRecipient($app_id){
        return AppRecipients::find()->select('to')->where(['app_id' => $app_id])->column();
    }

    public static function coment($app_id)
    {
        $user_id = Yii::$app->user->identity->id;
        $coment = (new \yii\db\Query())
            ->select(['a.message', 'a.files', 'a.date', 'u.avatar', 'u.first_name', 'u.last_name', 'u.specialization', 'u.id'])
            ->from(['a' => 'app_recipients'])
            ->innerJoin('user u','a.to=u.id')
            ->where(['a.from' => $user_id, 'app_id' =>$app_id])->all();
        
        return $coment;
    }

}

account/controllers/ApplicationController.php
<?php

namespace frontend\account\controllers;

use frontend\account\models\AppRecipients;
use yii;
use frontend\account\models\Application;
use common\models\User;
use yii\helpers\ArrayHelper;


class ApplicationController extends \yii\web\Controller
{

    public function actionIndex()
    {
        $create_app = Yii::$app->urlManager->createUrl(['/account/application/create_app']);
        $model = new Application();
        if ($model->load(Yii::$app->request->post()) && $model->uploadApp()) {
            return $this->redirect(['index']);
        }
        $user_id = \Yii::$app->user->identity->id;
        $app = (new \yii\db\Query())
            ->select(['a.id_app', 'a.title_app', 'a.url_app', 'a.description_app', 'a.id_folder', 'u.first_name', 'u.last_name', 'u.specialization', 'u.avatar', 'r.status', 'r.id', 'r.message', 'r.files', 'r.date'])
            ->from(['a' => 'application', 'r' => 'app_recipients' , 'u' => 'user'])
            ->where(['r.to' => $user_id])->andWhere('r.from=u.id')->andWhere('r.app_id = a.id_app')
            ->orderBy('id_app DESC')->all();
        $curent_user = User::find()->select(['first_name', 'last_name','specialization', 'avatar'])->where(['id' => $user_id])->asArray()->one();
        return $this->render('index', [
            'model' => $model,
            'create_url' => $create_app,
            'app' => $app,
            'curent_user' =>$curent_user,

        ]);
    }

    public function actionAppsend()
    {
        $user_id = \Yii::$app->user->identity->id;
        $models = Application::find()->where(['user_id' => $user_id])->orderBy('id_app DESC')->asArray()->all();
        $user = User::find()->select(['first_name', 'last_name', 'avatar', 'specialization'])->where(['id' => $user_id])->one();
        if (!$user->avatar) {
            $user->avatar = 'camera3.png';
        }
        return $this->render('appsend', [
            'models' => $models,
            'user' => $user,
        ]);

    }

    protected function findModel($id)
    {
        if (($model = Application::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
// удаление созданой заявки
    public function actionDelete($id)
    {
        $model = (new \yii\db\Query())->select(['url_app'])->from(['application'])->where(['id_app' => $id])->one();
        if ($model[url_app] != null) {
            $file = explode('|', $model[url_app]);
            foreach ($file as $each_file) {
                unlink(Yii::getAlias('@media') . '/application/new_app/' . $each_file);
            }
        }
        $this->findModel($id)->delete();
        return $this->redirect(['appsend']);

    }

    public function actionRead()
    {
       $app_id = $_POST['app_id'];
       $user_id = \Yii::$app->user->identity->id;
       Yii::$app->db->createCommand()->update("app_recipients", ["status" => 1], ['to'=>$user_id, 'app_id'=>$app_id])->execute();
    }
    // удаление входящей заявки
    public function actionRemove($id)
    {
        AppRecipients::findOne($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionSend()
    {
        $user_id = \Yii::$app->user->identity->id;
        $currentUser  = User::findOne($user_id);
        $path1 = Yii::getAlias('@media') . '/temp/';
        $path2 = Yii::getAlias('@media') . '/application/send_app/';
        $i = -1;
        $files = "";
        if (isset($_FILES)) {
            foreach( $_FILES as $file ){
                $temp = explode("/", $file['type']);

                if($temp[1] == 'doc' || $temp[1] == 'txt'|| $temp[1] == 'rtf'|| $temp[1] == 'jpg'|| $temp[1] == 'png' || $temp[1] == 'rtf' || $temp[1] == 'jpeg') {
                    $i++;
                    $ext = '.' . $temp[1];
                    $name = time().rand(111,999);

                    if( stristr ($_REQUEST['fileNames'], $file['name']) != false ){
                        $file_name[$i] = rand(111, 999)."_".$file['name'];
                        move_uploaded_file($file['tmp_name'] , $path1.$name.$ext );
                        copy( $path1.$name.$ext , $path2.$file_name[$i] );
                        $files .= $file_name[$i];
                        $files .= "|";
                    }

                }
                if (!empty($files)){
                    $add = substr($files, 0, -1);
                    Yii::$app->db->createCommand()->update("app_recipients", ["message"=>$_REQUEST['text'],"files" => $add ],['to'=>$user_id, 'app_id'=>$_REQUEST['app_id']])->execute();
                }else{
                    Yii::$app->db->createCommand()->update("app_recipients", ["message"=>$_REQUEST['text']],['to'=>$user_id, 'app_id'=>$_REQUEST['app_id']])->execute();
                }

            }

            $data['sender_avatar'] = $currentUser->avatar;
            $data['sender_specialization'] = $currentUser->specialization;
            $data['sender_username'] = $currentUser->first_name . " " . $currentUser->last_name;
            $data['url_avatar'] = Yii::getAlias('@avatar/'.$data['sender_avatar']);
            $data['file_name'] = $file_name;
            $data['path'] = $path2;
            $data['message'] = $_REQUEST['text'];
            $data['created_at'] = date("Y-m-d H:m:s");
            $data = json_encode($data);

            return $data;
        }

    }

    public function actionText()
    {
        $user_id = \Yii::$app->user->identity->id;
        $currentUser  = User::findOne($user_id);
        Yii::$app->db->createCommand()->update("app_recipients", ["message"=>$_REQUEST['text']],['to'=>$user_id, 'app_id'=>$_REQUEST['app_id']])->execute();
        $data['sender_avatar'] = $currentUser->avatar;
        $data['sender_username'] = $currentUser->first_name ." ". $currentUser->last_name;
        $data['url_avatar'] = Yii::getAlias('@avatar/'.$data['sender_avatar']);
        $data['message'] = $_REQUEST['text'];
        $data['sender_specialization'] = $currentUser->specialization;
        $data['created_at'] = date("Y-m-d H:m:s");
        $data = json_encode($data);

        return $data;
    }


}

account/views/application/appsend.php
<?php
use frontend\account\models\Application;
use yii\helpers\Url;
use frontend\account\models\AppRecipients;

$this->title = Yii::t('titles', 'account').Yii::t('titles','app_send');
$this->params['breadcrumbs'][] = $this->title;
?>
    <!--START CENTER-->
    <div class="col-lg-7  central-content centralScroll">
        <div class="content page-catalog page-in-catalog in-order applications">
            <div class="row">
                <h5><?= Yii::t('account', 'application_send') ?></h5>
                <?php if ($models) {
                    foreach ($models as $app) { ?>
                        <h4 class="promote promote-bottom"><?= $app['title_app']; ?> </h4>
                        <p class="upload-portfolio download-portfolio del" url=""><?= Yii::t('account', 'button_delete') ?><a
                                href="<?= Url::to(['application/delete', 'id' => $app['id_app']]); ?>"></a></p>
                        <div class="clearfix"></div>
                        <div class="send-to">
                            <span><?= Yii::t('account', 'application_to') ?>:</span>
                            <ul class="send">
                                <?php $recipients = Application::findRecipient(['app_id' => $app['id_app']]);
                                foreach ($recipients as $recipient) {
                                    ?>
                                    <li value="<?= $recipient; ?>"><a href="#"><img src="/images/team1.png" alt=""></a>
                                    </li>
                                <?php } ?>
                            </ul>
                            <p><?= $app['description_app']; ?></p>
                        </div>
                        <div class="send-to-img">
                            <div class="user-ava">
                                <img src="<?= Yii::getAlias('@avatar/' . $user->avatar); ?>" alt="">
                            </div>
                            <p class="name"><?= $user->first_name . ' ' . $user->last_name ?>
                                <span><?= $user->specialization; ?></span>
                            </p>
                        </div>
                        <a href="#" class="title atachFile"><i class="icon-silhouette107"></i><?= Yii::t('account', 'application_atach') ?></a>
                        <div class="atached" style="display: none">
                            <?php if ($app['id_folder']) {
                                $folder = Application::findFolder(['id_folder' => $app['id_folder'] ]); ?>
                                <div class="folder">
                                    <div class="clearfix"></div>
                                    <div class="name-folder ">
                                        <div class="folder-img change_f">
                                            <?php foreach($folder['0']['image'] as $image) : ?>
                                                <img src="/images/<?= $image['miniature_img']; ?>" alt="">
                                            <?php endforeach; ?>
                                            <div class="folder-bottom">
                                                <p><?= $folder[0]['folder']['title'] ?></p>
                                                <ul>
                                                    <li><a class="re_folder" url="<?= Url::to(['order/rename']); ?>"
                                                           href="#"><i class="icon-edit45"></i>Rename</a></li>
                                                    <li><a class="del_folder" url="<?= Url::to(['order/delete']); ?>"
                                                           href="#"><i class="icon-rubbish"></i>Delete</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                            <div class="clearfix"></div>
                            <?php if ($app['url_app']) {
                                $filess = explode('|', $app['url_app']); ?>
                                <ul class="load-files">
                                    <?php foreach ($filess as $file) { ?>
                                        <li><a href="<?= Yii::getAlias('@application/new_app/' . $file); ?>"
                                               download><?= substr($file, 4); ?></a><? ?></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                        <div class="reviews aplication">

                                <h4 class="promote"><?= Yii::t('account', 'application_review') ?></h4>
                            <?php $coment = Application::coment(['app_id' => $app['id_app']]); ?>
                                <?php foreach($coment as $one_coment): ?>
                                    <?php if(isset($one_coment['message']) || isset($one_coment['file'])){ ?>
                                    <div class="reviews-comment">
                                        <div class="reviews-photo">
                                            <img src="<?= Yii::getAlias('@avatar/' . $one_coment['avatar']); ?>" alt="">
                                            <p class="name"><?= $one_coment['first_name'] . ' ' . $one_coment['last_name']; ?><span><?= $one_coment['specialization']?></span></p>
                                            <div class="send-chat-message">
                                                <a href="#"><i class="icon-black218"></i></a>
                                            </div>
                                        </div>
                                        <div class="my-content-messages">
                                            <p><?= $one_coment['message'] ?></p>
                                            <?php if ($one_coment['files']) { ?>
                                                <?php $files_send = explode('|', $one_coment['files']); ?>
                                                <ul class='uploading-files'>
                                                    <?php foreach ($files_send as $send) : ?>
                                                        <li>
                                                            <a href="<?= Yii::getAlias('@application/send_app/' . $send); ?>" download><?= substr($send, 4); ?></a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            <?php } ?>
                                        </div>
                                        <p class="data"><?= $one_coment['date']; ?></p>
                                    </div>
                                        <?php }?>
                                <?php endforeach; ?>

                        </div>
                        <hr class="sline">
                    <?php }
                } else { ?>
                    <div class="empty-app">
                        <br>
                        <a href="/account/order/index"><?= Yii::t('account', 'application_create') ?></a>
                    </div>
                <?php } ?>
            </div>

        </div>

        <div class="row">
            <?= frontend\widgets\Banner::widget(['position' => 'bottom']);?>
        </div>
    </div>
    <!--END CENTER-->
<?php //$this->registerJsFile('js/common.js', ['depends' => 'frontend\assets\AppAsset']); ?>
<?php $this->registerJsFile('js/setOptions.js', ['depends' => 'frontend\assets\AppAsset']); ?>
<?php $this->registerJsFile('js/new-js.js', ['depends' => 'frontend\assets\AppAsset']); ?>

account/views/application/index.php
<?php

use frontend\account\models\Application;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;


$this->title = Yii::t('titles', 'account').Yii::t('titles','app_inbox');
$this->params['breadcrumbs'][] = $this->title;

?>
    <!--START CENTER-->
    <div class="col-lg-7 central-content centralScroll">
        <div class="content page-catalog page-in-catalog in-order applications inbox">
            <div class="row">
                <h5><?= Yii::t('account', 'inbox') ?></h5>
                <?php if ($app) { ?>
                    <?php foreach ($app as $model) : ?>
                        <div class="<?php if ($model['status'] == 0){ echo'new-messages'; } ?>">

                            <p class="upload-portfolio download-portfolio del" url=""><?= Yii::t('account', 'button_delete') ?>
                                <a href="<?= Url::to(['application/remove', 'id' => $model['id']]); ?>"></a>
                            </p>
                            <div class="inbox_app">
                                <h4 class="promote promote-bottom"><?= $model['title_app']; ?></h4>
                                <div style="display: none" class="status_app"><?= $model['status']; ?></div>
                                <div class="clearfix"></div>
                                <div class="send-to" id_app="<?= $model['id_app'] ?>">
                                    <p><?= $model['description_app']; ?></p>
                                </div>
                                <div class="send-to-img">
                                    <div class="user-ava">
                                        <img src="<?= Yii::getAlias('@avatar/' . $model['avatar']); ?>" alt="">
                                    </div>
                                    <p class="name"><?= $model['first_name'] . ' ' . $model['last_name']; ?>
                                    <span><?= $model['specialization']; ?></span></p>
                                </div>

                            </div>
                            <a href="#" class="title atachFile"><i class="icon-silhouette107"></i><?= Yii::t('account', 'application_atach') ?></a>
                            <div class="atached" style="display: none">
                                <?php if ($model['id_folder']) { ?>
                                    <?php $folder = Application::findFolder(['id_folder' => $app['id_folder'] ]); ?>
                                    <div class="folder">
                                        <div class="clearfix"></div>
                                        <div class="name-folder ">
                                            <div class="folder-img">
                                                <?php foreach($folder['0']['image'] as $image) : ?>
                                                    <img src="/images/<?= $image['miniature_img']; ?>" alt="">
                                                <?php endforeach; ?>
                                                <div class="folder-bottom">
                                                    <p><?= $folder[0]['title'] ?></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <div class="clearfix"></div>
                                <?php if ($model['url_app']) { ?>
                                    <?php $filess = explode('|', $model['url_app']); ?>
                                    <ul class="load-files">
                                        <?php foreach ($filess as $file) : ?>
                                            <li>
                                                <a href="<?= Yii::getAlias('@application/new_app/' . $file); ?>" download><?= substr($file, 4); ?></a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php } ?>
                            </div>
                            <?php if ($model['message'] || $model['files']) { ?>

                            <div class="reviews aplication">
                                <h4 class="promote"><?= Yii::t('account', 'application_review') ?></h4>

                                    <div class="reviews-comment">
                                        <div class="reviews-photo">
                                            <img src="<?= Yii::getAlias('@avatar/' . $curent_user['avatar']); ?>" alt="">
                                            <p class="name"><?= $curent_user['first_name'] . ' ' . $curent_user['last_name']; ?>
                                            <span><?= $curent_user['specialization']; ?></span></p>
                                        </div>
                                        <div class="my-content-messages">
                                            <p><?= $model['message']; ?></p>
                                            <?php if ($model['files']) { ?>
                                                <?php $files_send = explode('|', $model['files']); ?>
                                                <ul class='uploading-files'>
                                                    <?php foreach ($files_send as $send) : ?>
                                                        <li>
                                                            <a href="<?= Yii::getAlias('@application/send_app/' . $send); ?>" download><?= substr($send, 4); ?></a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            <?php } ?>
                                        </div>
                                        <p class="data"><?= $model['date']; ?></p>
                                    </div>

                            </div>
                            <?php } else { ?>

                            <div class="app_coment" send_id_app="<?= $model['id_app'] ?>" style="display: none">
                                <form action="" enctype="multipart/form-data" class="answer-form">
                                    <textarea name="#" class="app_review" required placeholder="<?= Yii::t('account', 'profile_reviews_place') ?>"></textarea>
                                    <div class="app_answer">
                                        <input type="file" class="answer_file" name="file"  accept=".txt, .pdf, .rtf, .doc, .jpg, .png" multiple="">
                                        <i class="icon-symbols"></i>
                                    </div>
                                    <div class="block-button">
                                        <input class="button submit-app" id_app="<?= $model['id_app'] ?>" value="<?= Yii::t('account', 'send') ?>" type="submit">
                                    </div>
                                </form>
                            </div>
                                <?php } ?>
                            <div class="input-app-file"></div>
                        </div>
                        <hr class="sline">
                        <div class="clearfix"></div>

                    <?php endforeach; ?>
                <?php } else {?>
                    <br>
                    <?= Yii::t('account', 'application_list'); ?>
                <?php } ?>

            </div>

        </div>

        <div class="row">
            <?= frontend\widgets\Banner::widget(['position' => 'bottom']);?>
        </div>

    </div>


    <!--END CENTER-->
<?php $this->registerJsFile('js/setOptions.js', ['depends' => 'frontend\assets\AppAsset']); ?>